### ISSUE TITLE
OSD render stops with "Null or empty decoder buffer."

### ISSUE THREAD

**Issue by ooZberg** [fpv-wtf/wtfos-configurator#426] opened 2024-06-19 18:30 UTC
### Device

Goggles V2

### Operating System (Including version)

msp-osd v0.12.2

### Browser

Version 125.0.6422.113 (Official Build) (x86_64)

### Trace ID (bottom left of the configurator screen)

e200ac2e-4a78-4e67-aa5a-6147603b4ba8

### Describe the issue

Old DVR files created previously with map-osd v0.10.x works fine also today, they render properly at https://fpv.wtf/osd-overlay

New DVR files from after I upgraded to msp-osd v0.12.2 does not. If I upload a DVR file (mp4+osd) it will fail for almost all files >1 min in length.

The error I get is "Null or empty decoder buffer." from the VideoDecoder object

I have also tried with two separate DJI Vista units so it does not seam to be related to the VTX. I have tried also with different browser like Vivaldi and it gives exactly the same problem.

**Comment by j005u** [comment] 2024-11-27 19:13
Please try the new development version at https://develop.fpv.wtf/osd-overlay and let us know if the issue is fixed for you.

**Comment by j005u** [comment] 2024-11-28 11:46
According to multiple user reports the problem has been solved.

Closing this issue, please re-open if needed.

**Closed as completed by j005u** 2024-11-28 11:46 UTC
