### ISSUE TITLE
OSD Overlay has not been working for 7 days now!

### ISSUE THREAD

**Issue by FabioFPV100PORCENTO** [fpv-wtf/wtfos-configurator#431] opened 2024-11-14 19:15 UTC
### Device

Goggles V2

### Operating System (Including version)

win 10

### Browser

Chrome

### Trace ID (bottom left of the configurator screen)

2.3.0

### Describe the issue

OSD Overlay has not been working for 7 days now. The files are perfect (Video, OSD and STR).
I have already tested with files that I had already worked with, and now it no longer works.

**Comment by j005u** [comment] 2024-11-15 14:45
Thank you for the report. We've been able to replicate the issue - this only seems to affect some .mp4/.osd combination and not others. It's unclear at this point what the issue is, the last time we updated the configurator was 6 months ago.

We'll investigate and report back here when there's any news. It may take some time to get to the bottom of this though as the original OSD tool developer is no longer active.

**Comment by Jerry-cloud-1989** [comment] 2024-11-23 05:39
目前还是无法使用，请问是否有其他类似的替代方法

**Comment by j005u** [comment] 2024-11-27 19:13
Please try the new development version at https://develop.fpv.wtf/osd-overlay and let us know if the issue is fixed for you.

**Comment by j005u** [comment] 2024-11-28 11:45
According to multiple user reports the problem has been solved.

Closing this issue, please re-open if needed.

**Closed as completed by j005u** 2024-11-28 11:45 UTC
