### ISSUE TITLE
WTFOS installation becomes corrupt repeatedly & after the health check cleanup I need to re-root again

### ISSUE THREAD

**Issue by slup67** [fpv-wtf/wtfos-configurator#228] opened 2022-11-10 21:44 UTC
I suspect that this is similar to the closed case #192 ... but thought that I should report it.

Have 2 Vista units rooted with wtfos installed & the msp-os & FCC patches ... one is on a 6s build & another on a 4s. Using the V2 goggles & all, both Vistas and goggles are on 0606.

All is working solid on the 4s but not on the 6s ... the 6s repeatedly get it's wtfos stuck in the health checks & needs to be fixed there, after that I need to re-root, install wtfos again + the patches.

Think I've narrowed it down to that the 6s battery often creates a spark (arcing) when I connect the xt60 to the quad ... imagine that can create a current spike which makes the Vista change slot to 2 (similar to quickly connect & disconnect the battery)? The 4s quad batteries never generates arcing & it's maybe the reason for it to work reliably?

The other day I had the 6s quad powered on the bench & the OSD was working as it should in the goggles ... disconnected the battery, & an hour later I again connected the battery & got a pop sound due to arcing between the quad xt 60 & the battery xt60 ... & now the OSD wasn't working anymore. After connecting the Vista to the WTFOS configurator site the wtfos installation needed to be fixed.

Read that you were working on a long term solution for this ... any news when this can be addressed?

**Comment by j005u** [comment] 2022-11-10 21:54
I have a beta version of this ready to go, but we don't want to release it before we've been able to also release a low level recovery tool, which is still in the works. No specific ETAs I'm afraid, it's a somewhat complicated undertaking.

The consequence of not having a low level recovery tool is that if something goes horribly wrong, you don't have the 2nd slot to fall back on. While not super likely, it's still possible.

If the arc powers the vista on for somewhere between 0.3-1 seconds then that could entirely be the case. Haven't heard of anyone else having the exact same problem though, where it's this repeatable. I wonder if it's something specific about your build, or the vista itself.

If you have a smokestopper with a button, could you try booting the 6s quad with that, avoiding the ark, and seeing if the issue persists?

**Comment by slup67** [comment] 2022-11-10 22:49
It shouldn't be anything special or out of the ordinary with the "build" ... it's a BNF iFlight Nazgul Evoque.... with a bit fiddly xt60 position/location.

Don't have a smokestopper unfortunately ... but pretty certain the arcing can power on the Vista a couple tenth of a second, every time I hear that popping I just know that I don't have any OSD anymore.

Will let you know if I can get hold of a smokestopper & test ... meanwhile I've put on some electrical grease on the pins inside the xt60 to make it go in quicker & smoother (hoping that will prevent the arcing). Looking forward to something that can fix this ... saw something on your todo wall, a wtfos version 0.2?

**Comment by j005u** [comment] 2022-11-10 22:57
My 4S quads usually make a loud pop on plugin too, but that doesn't result in this behavior.

If you wish you can install the 0.2.0 beta by extracting this .ipk from the zip, using adb to upload it to the device and the command `opkg install wtfos-system_0.2.0_armv7-3.2.ipk`. [wtfos-system_0.2.0_armv7-3.2.zip](https://github.com/fpv-wtf/wtfos-configurator/files/9985164/wtfos-system_0.2.0_armv7-3.2.zip)

The risk is if something goes extremely wrong with both slots, then you'll have to wait until the recovery tool is ready to unbrick the vista.

**Comment by slup67** [comment] 2022-11-11 08:07
Thank's for the offer, but don't want to risk bricking my 5" ... rather wait for a solution you guys believe is safe. Just wanted you to know about the problem.

Keep it up guys, what you've done so far is impressive... I'm sure more jaw-dropping features will come in the future!

**Comment by Fluxone** [comment] 2022-11-12 17:54
same issue here. I have multiple stable roots on vista and AUs but have one Vista unit that will not keep the root/wtfos in proper slot - The attempt to fix by the web app never seems to work and requires re-root and reinstall of wtfos each time.

I think I have isolated the cause, the FC on this quad does not seem to restrict through power to the Vista when connected via usb (to betaflight for instance). The Vista gets probably less than required voltage through the fc/usb connection and does not boot fully (only red light on vista when fc is plugged into usb).

If I root and install WTFOS and NEVER plug my FC back into USB power the root is stable. As soon as I plug my FC into USB to tune or adjust I break the root/wtfos.

Hope this info helps to solve this, my Vista is hardwired to FC so I cant easily disconnect the Vista when I need to adjust the FC settings - I will just have to re-root/install WTFOS, AFTER each time I adjust the FC.

**Comment by slup67** [comment] 2022-11-12 20:29
Yep, that was actually my initial suspicion also ... but couldn't repeat it as reliable as just plugging in the xt60. The Vista where it happens for me is on a iFlight Nazgul Evoque which have covered sides hiding the Vista's led light, so can't say if it sometimes goes red shortly.

But have noticed another thing that possibly can indicate that the VTX shortly gets power through a FC usb connection ... normally a FC usb connection is quiet, meaning no beeping (have "beacon beeping on usb connected" disconnected in BF). But sometimes the "quad" makes a very short beep on FC usb connection... especially if I change something in BF that require "save & reboot", when rebooting that short beep can come. This suspicion was so strong that I actually turned off auto reboot on the welcome page in BF.

The Vista in the Nazgul is connected to the FC with a connector ... so not soldered, but to access it the Gopro mount & top plate needs to be taken off... nothing I want to do over & over again to see if a disconnected Vista during BF adjustments can stop the wtfos corruption.

**Comment by Spit29** [comment] 2022-11-13 20:13
Thought I'd contribute as I'm the one who opened case https://github.com/fpv-wtf/wtfos-configurator/issues/192

I never had the issue again (losing root) as long as I'm quick to connect batteries and make sure not to disconnect too quickly after powering up. That was with a 4s battery and a 6s battery on 2 different drones.

**Comment by j005u** [comment] 2022-11-13 22:49
I could see the Vista exceeding power draw limits on USB for sure once the RF stage is inited for example, which would interrupt boot and therefor switch slots.

The DJI slot system just doesn't like this in principle sadly. The only fix I can think of is installing in both slots, for which there's a beta available above. Like stated however, we don't feel comfortable releasing it fully before the low level recovery tool is finished.

**Comment by Fluxone** [comment] 2022-11-13 22:52
I cant comment on the other users issues but mine is definitely the poor power management of the FC/USB. I put many packs through yesterday with no prob, but as soon as I connect the FC to USB without full power to the Vista it breaks the slots.

Simple solution is to just power up and allow full boot with battery before you connect FC to USB for tuning. Like I said  I flew all day yesterday with this workaround.

**Comment by TomAlperin** [comment] 2022-11-16 03:36
I am also seeing this issue. The lone quad that seems to have had the issue occur the most had a ViFly installed where the button is not easily accessible although I have disabled the buzzer by plugging at least a few times before the issue occurred.

**Comment by robertrypula** [comment] 2022-12-13 20:20
Just testing. I already installed v0.2.0 on the googles side but there is a problem in loading packages:

![image](https://user-images.githubusercontent.com/6407731/207435553-891b0396-a059-42e8-b54a-686d52ec01ee.png)

**Comment by stylesuxx** [comment] 2022-12-13 20:47
@robertrypula you did install wtfOS, not just open the package page, right?

**Comment by robertrypula** [comment] 2022-12-13 20:49
Yes, WTF OS was installed before and then I went into packages page. 404 issue is gone now - I think I rebooted the googles and it worked fine afterwards.

**Comment by stylesuxx** [comment] 2022-12-13 20:55
Yeah the 404 is kind of a false positive in this case it's how routing works with this stack in combination with GitHub pages...

**Comment by slup67** [comment] 2022-12-13 21:09
Also had that unpopulated package page when I entered it directly after updating the wtfos installation, both for the goggles & vista... just power cycled them & reconnected & all packages was there again.

**Comment by j005u** [comment] 2022-12-13 23:32
Glad it's working well for everyone.

Closing as the issue should be solved now.

**Closed by j005u** 2022-12-13 23:32 UTC
Labels: support
