### ISSUE TITLE
Could not connect to device

### ISSUE THREAD

**Issue by AdrThomas** [fpv-wtf/wtfos-configurator#332] opened 2023-04-07 16:07 UTC
### Device

Goggles V1

### Describe the issue

Could not connect to device, make sure that adb server is not running on your machine (adb kill-server) and that you are not connected in another tab/window.

**Comment by j005u** [comment] 2023-04-09 17:19
Please give our latest driver installer a try and see if it helps: https://github.com/fpv-wtf/driver-installer/releases/tag/v1.1.0

**Comment by j005u** [comment] 2023-04-09 19:00
Update: I now beleive the problem is different. Please go to https://fpv.wtf/root and root the device again. It may be normal in some circumstances to need to do this more than once.

**Comment by stylesuxx** [comment] 2023-04-12 08:38
@AdrThomas any update on this, otherwise I will close the issue.

**Comment by stylesuxx** [comment] 2023-05-16 08:46
No response, closed.

**Closed by stylesuxx** 2023-05-16 08:46 UTC
Labels: support
